"""Phase-0 discovery: scan a repo for identity values, emit a draft identikit.toml.

The template author seeds the identity fields (name + current value + metadata);
`discover` finds every occurrence, groups them by (field, mode), detects path-name
renames and lockfile regenerations, and renders a reviewable config. The output is
a draft — the author curates it before committing.

Reuses ``doctor.iter_text_files`` for the exclude/binary logic.
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

from identikit.common import IdentityField
from identikit.doctor import iter_text_files

LOCKFILES: dict[str, list[str]] = {
    "uv.lock": ["uv", "lock"],
    "bun.lock": ["bun", "install"],
}
STRUCTURED_SUFFIXES = {".toml"}

Scan = dict[tuple[str, str], dict[str, int]]


def _mode(path: Path) -> str:
    return "structured" if path.suffix in STRUCTURED_SUFFIXES else "text"


def scan_values(
    root: Path,
    identity: dict[str, IdentityField],
    exclude_paths: tuple[str, ...] = (),
) -> Scan:
    """Map ``(field, mode) → {relpath: count}`` for every identity occurrence."""
    hits: Scan = defaultdict(dict)
    for path in iter_text_files(root, exclude_paths):
        if path.name in LOCKFILES:
            continue  # lockfiles are regenerated, never text-replaced
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        rel = str(path.relative_to(root))
        mode = _mode(path)
        for name, ident in identity.items():
            count = text.count(ident.value)
            if count:
                hits[(name, mode)][rel] = count
    return hits


def find_renames(
    root: Path, identity: dict[str, IdentityField]
) -> list[tuple[str, str]]:
    """Path-name hits implying a ``[[rename]]``, sorted longest-first."""
    renames: list[tuple[str, str]] = []
    seen: set[str] = set()
    for path in sorted(root.rglob("*")):
        try:
            rel = path.relative_to(root)
        except ValueError:
            continue
        if rel.parts and rel.parts[0] in {".git", "node_modules", ".venv"}:
            continue
        for name, ident in identity.items():
            if ident.value and ident.value in rel.name:
                src = str(rel)
                if src in seen:
                    continue
                seen.add(src)
                dst = str(
                    rel.with_name(rel.name.replace(ident.value, "{" + name + "}"))
                )
                renames.append((src, dst))
                break
    renames.sort(key=lambda pair: -len(pair[0]))
    return renames


def find_regenerates(root: Path) -> list[tuple[str, list[str]]]:
    """Lockfiles present in the repo → ``[[regenerate]]`` blocks."""
    return [(name, cmd) for name, cmd in LOCKFILES.items() if (root / name).exists()]


def _toml_str_list(items: list[str], indent: str = "  ") -> str:
    if not items:
        return "[]"
    body = "\n".join(f'{indent}"{i}",' for i in items)
    return f"[\n{body}\n]"


def generate(
    root: Path,
    identity: dict[str, IdentityField],
    exclude_paths: tuple[str, ...] = (),
) -> str:
    """Render a draft ``identikit.toml`` for ``root``."""
    scan = scan_values(root, identity, exclude_paths)
    renames = find_renames(root, identity)
    regenerates = find_regenerates(root)

    out: list[str] = [
        "# identikit.toml — DRAFT generated by `identikit discover`.",
        "# Review: 'text' mode does longest-first string replacement; reclassify",
        "# intent-bearing files as 'structured', and prune historical occurrences.",
        "",
    ]

    for name, ident in identity.items():
        out += [
            f"[identity.{name}]",
            f'value    = "{ident.value}"',
            f'validate = "{ident.validate}"',
            f'prompt   = "{ident.prompt}"',
        ]
        if ident.derive:
            out.append(f'derive   = "{ident.derive}"')
        out.append("")

    for name, mode in sorted(scan.keys()):
        files = scan[(name, mode)]
        total = sum(files.values())
        out += [
            f"# {name} ({mode}) — {total} occurrences in {len(files)} files",
            "[[replace]]",
            f'field = "{name}"',
            f"files = {_toml_str_list(sorted(files))}",
            f'mode  = "{mode}"',
            "",
        ]

    for src, dst in renames:
        out += ["[[rename]]", f'from = "{src}"', f'to   = "{dst}"', ""]

    for path, cmd in regenerates:
        cmd_str = ", ".join(f'"{c}"' for c in cmd)
        out += ["[[regenerate]]", f'path    = "{path}"', f"command = [{cmd_str}]", ""]

    return "\n".join(out)


def summary(scan: Scan) -> str:
    """Human-readable occurrence summary."""
    lines = ["Discovery summary", "================="]
    grand = 0
    files: set[str] = set()
    for (name, mode), hits in sorted(scan.items()):
        total = sum(hits.values())
        grand += total
        files.update(hits)
        lines.append(f"  {name:<16} [{mode:<10}] {total:>4}× in {len(hits):>3} files")
    lines.append(f"  {'TOTAL':<16} {'':<12} {grand:>4}× in {len(files):>3} files")
    return "\n".join(lines)
